@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_WITH_LEGEND()

title Открытие депозитов

Person(client, "Клиент банка", "Физическое лицо, преимущественно старшего возраста, предпочитает офлайн-обслуживание")
Person(backOfficeDeposit, "Менеджер депозитов", "Сотрудник бэк-офиса по депозитным продуктам")
Person(callCenterOp, "Менеджер кол-центра", "Сотрудник внутреннего кол-центра банка")

System(abs, "АБС (Автоматизированная банковская система)", "Основная система учёта операций по счетам и бухгалтерия. Десктоп-клиент Delphi + Oracle DB (PL-SQL). Разработка внутри банка")

System(internetBank, "Интернет-банк", "Клиент-серверная система для проведения платежей и открытия текущих счетов. ASP.NET MVC 4.5 + MS SQL. Монолит на платформе подрядчика")

System(callCenterSystem, "Система кол-центра", "CRM-платформа подрядчика для автоматизации работы кол-центра. React.js + Java Spring Boot + PostgreSQL. Микросервисная архитектура")

System(website, "Сайт банка", "Маркетинговая информация о продуктах и услугах банка. PHP + React.js. Собственная разработка")

System_Ext(smsGateway, "СМС-шлюз", "Шлюз телеком-оператора для отправки СМС-уведомлений")

Rel(smsGateway, client, "Доставляет СМС-уведомление с предложением на открытие депозита из интернет-банка; подтверждение заявки на открытие депозита с сайта", "SMS")

Rel(client, website, "Просматривает актуальные депозитные ставки. Подаёт заявку на открытие депозита")
Rel(client, internetBank, "Просматривает персонализированные депозитные ставки; одтверждает заявку на открытие депозита и подтверждает заявку кодом из СМС")

Rel(website, abs, "Передаёт заявку о депозите с сайта", "Kafka")
Rel(internetBank, abs, "Передаёт заявку о депозите из интернет-банка", "Kafka")

Rel(abs, callCenterSystem, "Передаёт заявку о депозите в колл-центр", "Kafka")
Rel(abs, smsGateway, "Передаёт СМС для отправки по заявке на открытие депозита из интернет-банка")
Rel(abs, smsGateway, "Передаёт СМС для подтверждения заявки на открытие депозита с сайта")

Rel(callCenterSystem, callCenterOp, "Назначает заявку на открытие депозита менеджеру")
Rel(callCenterOp, client, "Связывается с клиентом для предложений условий по открытию депозита ")


Rel(backOfficeDeposit, abs, "Обрабатывает заявку на открытие депозита, указывает ставку, направляет СМС с информацией клиенту")


SHOW_LEGEND()
@enduml